CREATE TABLE IF NOT EXISTS RawData (
    pid INTEGER,
    name TEXT,
    num_tracks INTEGER,
    num_albums INTEGER,
    num_artists INTEGER,
    pl_duration_ms INTEGER,
    num_followers INTEGER,
    collaborative TEXT,
    pos INTEGER,
    track_name TEXT,
    album_name TEXT,
    artist_name TEXT,
    duration_ms INTEGER,
    track_uri TEXT,
    album_uri TEXT,
    artist_uri TEXT);
