CREATE TABLE IF NOT EXISTS RawData (
    pl_pid INTEGER,
    pl_name TEXT,
    pl_num_tracks INTEGER,
    pl_num_albums INTEGER,
    pl_num_artists INTEGER,
    pl_duration_ms INTEGER,
    pl_num_followers INTEGER,
    pl_collaborative TEXT,
    pos INTEGER,
    track_name TEXT,
    album_name TEXT,
    artist_name TEXT,
    duration_ms INTEGER,
    track_uri TEXT,
    album_uri TEXT,
    artist_uri TEXT);
